# Generated by Django 4.1.6 on 2023-02-15 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster', models.IntegerField(default=0, verbose_name='Итоговая сила монстра')),
                ('player', models.IntegerField(default=0, verbose_name='Итоговая сила игрока/команды')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='L0OA8', max_length=5, unique=True, verbose_name='Номер комнаты')),
                ('duration', models.TimeField(verbose_name='Продолжительность игры')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Дата старта')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='RoomPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Дата старта')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile', verbose_name='Игрок')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.rooms', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Игрок комнаты',
                'verbose_name_plural': 'Игрок комнаты',
            },
        ),
        migrations.CreateModel(
            name='RoomBattlePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField(default=0, verbose_name='Усиления игрока')),
                ('battle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.roombattle', verbose_name='Битва')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.roomplayer', verbose_name='Игрок')),
            ],
        ),
        migrations.CreateModel(
            name='RoomBattleMonster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavel', models.IntegerField(default=2, verbose_name='Сила монстра')),
                ('power', models.IntegerField(default=0, verbose_name='Усиления монстра')),
                ('battle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.roombattle', verbose_name='Битва')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('W', 'Эльф'), ('M', 'Дварф'), ('T', 'Хафлингом')], default='O', max_length=1, verbose_name='Класс')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.roomplayer', verbose_name='Игрок')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField(default=0, verbose_name='Мощность')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.roomplayer', verbose_name='Игрок')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerLeavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavel', models.IntegerField(default=1, verbose_name='Уровень')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.roomplayer', verbose_name='Игрок')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('W', 'Воин'), ('M', 'Волшебник'), ('T', 'Вор'), ('C', 'Клирик')], default='O', max_length=1, verbose_name='Класс')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.roomplayer', verbose_name='Игрок')),
            ],
        ),
    ]
