# Generated by Django 4.1.6 on 2023-03-27 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roomAdmin', to=settings.AUTH_USER_MODEL, verbose_name='Админ комнаты'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roomOwner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец комнаты'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='rules_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.rulesbook', verbose_name='Книга правил для комнаты'),
        ),
        migrations.AddField(
            model_name='roomplayer',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roomPlayer', to=settings.AUTH_USER_MODEL, verbose_name='Игрок'),
        ),
        migrations.AddField(
            model_name='roomplayer',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to='room.rooms', verbose_name='Комната'),
        ),
        migrations.AddField(
            model_name='roombattleplayer',
            name='battle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.roombattle', verbose_name='Битва'),
        ),
        migrations.AddField(
            model_name='roombattleplayer',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.roomplayer', verbose_name='Игрок'),
        ),
        migrations.AddField(
            model_name='roombattlemonster',
            name='battle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.roombattle', verbose_name='Битва'),
        ),
        migrations.AddField(
            model_name='playerrace',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerRace', to='room.roomplayer', verbose_name='Игрок'),
        ),
        migrations.AddField(
            model_name='playerpower',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='power', to='room.roomplayer', verbose_name='Игрок'),
        ),
        migrations.AddField(
            model_name='playerleavel',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leavel', to='room.roomplayer', verbose_name='Игрок'),
        ),
        migrations.AddField(
            model_name='playerclass',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerClass', to='room.roomplayer', verbose_name='Игрок'),
        ),
    ]
