# Generated by Django 4.1.6 on 2023-09-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rooms",
            name="code",
            field=models.CharField(
                default="F1BDZ", max_length=5, unique=True, verbose_name="Номер комнаты"
            ),
        ),
    ]
