# Generated by Django 4.1.6 on 2023-02-15 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_gender'),
        ('room', '0002_roombattle_create_roombattle_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='leavel_to_win',
            field=models.IntegerField(default=10, verbose_name='Сколько нужно уровней для победы'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('O', 'Открытая'), ('C', 'Одиночная'), ('S', 'Закрытая')], default='O', max_length=1, verbose_name='Тип игры'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='rules_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.rulesbook', verbose_name='Книга правил для комнаты'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='code',
            field=models.CharField(default='TpibJ', max_length=5, unique=True, verbose_name='Номер комнаты'),
        ),
    ]
