# Generated by Django 4.1.6 on 2023-02-15 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_rooms_code_alter_rooms_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='code',
            field=models.CharField(default='RoV4Q', max_length=5, unique=True, verbose_name='Номер комнаты'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='duration',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Продолжительность игры'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('O', 'Открытая'), ('C', 'Одиночная'), ('S', 'Закрытая')], default='O', max_length=1, verbose_name='Тип игры'),
        ),
    ]
