# Generated by Django 4.1.6 on 2023-02-15 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_rulesbook_user'),
        ('room', '0005_alter_rooms_code_alter_rooms_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roomAdmin', to='users.profile', verbose_name='Админ комнаты'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roomOwner', to='users.profile', verbose_name='Владелец комнаты'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='code',
            field=models.CharField(default='Mkk5z', max_length=5, unique=True, verbose_name='Номер комнаты'),
        ),
    ]
