# Generated by Django 4.1.6 on 2023-02-15 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_rulesbook_user'),
        ('room', '0006_rooms_admin_rooms_owner_alter_rooms_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='end',
            field=models.BooleanField(default=True, verbose_name='Игра завершилась?'),
        ),
        migrations.AlterField(
            model_name='roomplayer',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roomPlayer', to='users.profile', verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='roomplayer',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to='room.rooms', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='code',
            field=models.CharField(default='eSqfy', max_length=5, unique=True, verbose_name='Номер комнаты'),
        ),
    ]
