# Generated by Django 4.1.6 on 2023-02-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_rooms_end_alter_roomplayer_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='code',
            field=models.CharField(default='9STH1', max_length=5, unique=True, verbose_name='Номер комнаты'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата старта'),
        ),
    ]
