# Generated by Django 4.1.6 on 2023-02-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_alter_rooms_code_alter_rooms_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomplayer',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Порядок игроков'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='code',
            field=models.CharField(default='kgPNa', max_length=5, unique=True, verbose_name='Номер комнаты'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='end',
            field=models.BooleanField(default=False, verbose_name='Игра завершилась?'),
        ),
    ]
