# Generated by Django 4.1.6 on 2023-02-16 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_roomplayer_order_alter_rooms_code_alter_rooms_end'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerclass',
            options={'ordering': ['-create']},
        ),
        migrations.AlterModelOptions(
            name='playerrace',
            options={'ordering': ['-create']},
        ),
        migrations.AlterModelOptions(
            name='roomplayer',
            options={'ordering': ['-order'], 'verbose_name': 'Игрок комнаты', 'verbose_name_plural': 'Игрок комнаты'},
        ),
        migrations.AlterField(
            model_name='playerclass',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerClass', to='room.roomplayer', verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='playerrace',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerRace', to='room.roomplayer', verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='code',
            field=models.CharField(default='zDEuw', max_length=5, unique=True, verbose_name='Номер комнаты'),
        ),
    ]
