# Generated by Django 4.1.6 on 2023-09-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0011_alter_rooms_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="rooms",
            name="only_verified_users",
            field=models.BooleanField(
                default=False,
                verbose_name="Только пользователи с подтверждённой почтой",
            ),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="code",
            field=models.CharField(
                default="e7nKx", max_length=5, unique=True, verbose_name="Номер комнаты"
            ),
        ),
    ]
