# Generated by Django 4.1.6 on 2023-09-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0012_rooms_only_verified_users_alter_rooms_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rooms",
            name="code",
            field=models.CharField(
                default="TIDKh",
                editable=False,
                max_length=5,
                unique=True,
                verbose_name="Номер комнаты",
            ),
        ),
    ]
