# Generated by Django 4.1.6 on 2023-09-22 09:57

from django.db import migrations, models
import room.models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0014_alter_rooms_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rooms",
            name="code",
            field=models.CharField(
                default=room.models.get_code,
                max_length=5,
                unique=True,
                verbose_name="Номер комнаты",
            ),
        ),
    ]
