# Generated by Django 4.1.6 on 2023-09-26 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0016_connectionrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectionrequest",
            name="create",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания заявки на подключение",
            ),
            preserve_default=False,
        ),
    ]
