# Generated by Django 4.1.6 on 2023-10-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0017_connectionrequest_create"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectionrequest",
            name="update",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата обновления заявки на подключение"
            ),
        ),
    ]
