# Generated by Django 4.1.6 on 2023-11-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0018_connectionrequest_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectionrequest",
            name="spectator",
            field=models.BooleanField(default=False, verbose_name="Зритель"),
        ),
    ]
