# Generated by Django 4.1.6 on 2023-12-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0022_roomplayer_last_request_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="rooms",
            name="change_permission",
            field=models.BooleanField(
                default=False,
                verbose_name="Игроки могут менять друг другу характеристики",
            ),
        ),
    ]
