# Generated by Django 4.1.6 on 2023-12-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0023_rooms_change_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerclass",
            name="value",
            field=models.CharField(
                choices=[
                    ("N", "Нет"),
                    ("W", "Воин"),
                    ("M", "Волшебник"),
                    ("T", "Вор"),
                    ("C", "Клирик"),
                    ("WM", "Воин/Волшебник"),
                    ("WT", "Воин/Вор"),
                    ("WC", "Воин/Клирик"),
                    ("MT", "Волшебник/Вор"),
                    ("MC", "Волшебник/Клирик"),
                    ("TC", "Вор/Клирик"),
                ],
                default="N",
                max_length=2,
                verbose_name="Класс",
            ),
        ),
        migrations.AlterField(
            model_name="playerrace",
            name="value",
            field=models.CharField(
                choices=[
                    ("H", "Человек"),
                    ("W", "Эльф"),
                    ("M", "Дварф"),
                    ("T", "Хафлингом"),
                    ("HW", "Человек/Эльф"),
                    ("HM", "Человек/Дварф"),
                    ("HT", "Человек/Хафлингом"),
                    ("WM", "Эльф/Дварф"),
                    ("WT", "Эльф/Хафлингом"),
                    ("MT", "Дварф/Хафлингом"),
                ],
                default="H",
                max_length=2,
                verbose_name="Класс",
            ),
        ),
    ]
