# Generated by Django 4.1.6 on 2023-02-11 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='users/profile/photo', verbose_name='Фото')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профиль пользователей',
                'ordering': ['create'],
            },
        ),
        migrations.CreateModel(
            name='RulesBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Владелец книги')),
            ],
            options={
                'verbose_name': 'Книга правил',
                'verbose_name_plural': 'Книга правил',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RulesSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Заголовок')),
                ('rules', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Правила')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.rulesbook', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Правило из книги',
                'verbose_name_plural': 'Правила из книги',
                'ordering': ['title'],
            },
        ),
    ]
