# Generated by Django 4.1.6 on 2023-09-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="language",
            field=models.CharField(
                choices=[
                    ("ru", "Русский"),
                    ("en", "Английский"),
                    ("de", "Немецкий"),
                    ("ch", "Китайский"),
                ],
                default="ru",
                max_length=2,
                verbose_name="Язык",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="name",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="имя пользователя"
            ),
        ),
    ]
