# Generated by Django 4.1.6 on 2023-09-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_customuser_language_alter_customuser_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                default="anonymus", max_length=30, verbose_name="username"
            ),
        ),
    ]
