# Generated by Django 4.1.6 on 2023-09-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_customuser_email_verify"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_confirmation_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
