# Generated by Django 4.1.6 on 2023-12-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_customuser_email_confirmation_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="guest",
            field=models.BooleanField(default=False),
        ),
    ]
