# Generated by Django 4.1.6 on 2023-09-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="metatag",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="metatags"),
        ),
    ]
